const Keyv = require("keyv");
global.fs = require('fs');
global.db = new Keyv('sqlite://database.sqlite');
global.path = require('path');
global.app = require('./server.js')();
global.Docker = require('dockerode');
global.docker = new Docker({ socketPath: '/var/run/docker.sock' });
global.config = require('../config.json');
global.WebSocket = require('ws');
global.wss = require('ws');
global.synapse = require('./synapse.js')
global.bodyParser = require('body-parser')
const { exec } = require('child_process');
global.exec = exec;
const { Server } = require('ssh2');
global.Server = Server